class_name GameImports

static var game_prefabs: Array[String] = [
	"EZ BreakableDoor",
	"HCZ BreakableDoor",
	"LCZ BreakableDoor",
	"sportTargetPrefab",
	"dboyTargetPrefab",
	"binaryTargetPrefab",
	"TantrumObj",
	"PrimitiveObjectToy",
	"LightSourceToy",
	"Scp018Projectile",
	"Scp2176Projectile",
	"Amnestic Cloud Hazard",
	"Scp018PedestalStructure Variant",
	"Scp207PedestalStructure Variant",
	"Scp244PedestalStructure Variant",
	"Scp268PedestalStructure Variant",
	"LargeGunLockerStructure",
	"RifleRackStructure",
	"MiscLocker",
	"GeneratorStructure",
	"Spawnable Work Station Structure",
	"RegularMedkitStructure",
	"AdrenalineMedkitStructure",
	"Scp500PedestalStructure Variant",
	"Scp1853PedestalStructure Variant",
	"Scp2176PedestalStructure Variant",
	"Scp1576PedestalStructure Variant",
	"HegProjectile",
	"FlashbangProjectile",
	"SCP-173_Ragdoll",
	"Ragdoll_1",
	"SCP-106_Ragdoll",
	"Ragdoll_4",
	"Ragdoll_7",
	"Ragdoll_6",
	"Ragdoll_8",
	"SCP-096_Ragdoll",
	"Ragdoll_10",
	"Ragdoll_Tut",
	"Ragdoll_12",
	"SCP-939_Ragdoll",
	"Scp3114_Ragdoll"
]

static var game_item_types: Array[String] = [
	"None",
	"KeycardJanitor",
	"KeycardScientist",
	"KeycardResearchCoordinator",
	"KeycardZoneManager",
	"KeycardGuard",
	"KeycardMTFPrivate",
	"KeycardContainmentEngineer",
	"KeycardMTFOperative",
	"KeycardMTFCaptain",
	"KeycardFacilityManager",
	"KeycardChaosInsurgency",
	"KeycardO5",
	"Radio",
	"GunCOM15",
	"Medkit",
	"Flashlight",
	"MicroHID",
	"SCP500",
	"SCP207",
	"Ammo12gauge",
	"GunE11SR",
	"GunCrossvec",
	"Ammo556x45",
	"GunFSP9",
	"GunLogicer",
	"GrenadeHE",
	"GrenadeFlash",
	"Ammo44cal",
	"Ammo762x39",
	"Ammo9x19",
	"GunCOM18",
	"SCP018",
	"SCP268",
	"Adrenaline",
	"Painkillers",
	"Coin",
	"ArmorLight",
	"ArmorCombat",
	"ArmorHeavy",
	"GunRevolver",
	"GunAK",
	"GunShotgun",
	"SCP330",
	"SCP2176",
	"SCP244a",
	"SCP244b",
	"SCP1853",
	"ParticleDisruptor",
	"GunCom45",
	"SCP1576",
	"Jailbird",
	"AntiSCP207",
	"GunFRMG0",
	"GunA7",
	"Lantern",
	"Snowball",
	"Coal",
	"SpecialCoal",
	"Tape"
]

static var game_room_names: Array[String] = [
	"Unnamed",
	"LczClassDSpawn",
	"LczComputerRoom",
	"LczCheckpointA",
	"LczCheckpointB",
	"LczToilets",
	"LczArmory",
	"Lcz173",
	"LczGlassroom",
	"Lcz330",
	"Lcz914",
	"LczGreenhouse",
	"LczAirlock",
	"HczCheckpointToEntranceZone",
	"HczCheckpointA",
	"HczCheckpointB",
	"HczWarhead",
	"Hcz049",
	"Hcz079",
	"Hcz096",
	"Hcz106",
	"Hcz939",
	"HczMicroHID",
	"HczArmory",
	"HczServers",
	"HczTesla",
	"EzCollapsedTunnel",
	"EzGateA",
	"EzGateB",
	"EzRedroom",
	"EzEvacShelter",
	"EzIntercom",
	"EzOfficeStoried",
	"EzOfficeLarge",
	"EzOfficeSmall",
	"Outside",
	"Pocket",
	"HczTestroom",
]

static var game_role_types: Array[String] = [
	"None",
	"Scp173",
	"ClassD",
	"Spectator",
	"Scp106",
	"NtfSpecialist",
	"Scp049",
	"Scientist",
	"Scp079",
	"ChaosConscript",
	"Scp096",
	"Scp0492",
	"NtfSergeant",
	"NtfCaptain",
	"NtfPrivate",
	"Tutorial",
	"FacilityGuard",
	"Scp939",
	"CustomRole",
	"ChaosRifleman",
	"ChaosMarauder",
	"ChaosRepressor",
	"Overwatch",
	"Filmmaker",
	"Scp3114",
]

static var mapgeno_door_type: Array[String] = [
  "EntranceContainmentDoor",
  "LightContainmentDoor",
  "HeavyContainmentDoor", 
]

static var keycard_permissions: Dictionary = {
	"Checkpoints": 00000001,
	"ExitGates": 00000010,
	"Intercom": 00000100,
	"AlphaWarhead": 00001000,
	"ContainmentLevelOne": 00010000,
	"ContainmentLevelTwo": 00100000,
	"ContainmentLevelThree": 01000000,
	"ArmoryLevelOne": 10000000,
	"ArmoryLevelTwo": 100000000,
	"ArmoryLevelThree": 1000000000,
	"ScpOverride": 10000000000,
}

static var door_lock_type: Dictionary = {
	"Regular079": 00000001,
	"Lockdown079": 00000010,
	"Warhead": 00000100,
	"AdminCommand": 00001000,
	"DecontLockdown": 00010000,
	"DecontEvacuate": 00100000,
	"SpecialDoorFeature": 01000000,
	"NoPower": 10000000,
	"Isolation": 100000000,
	"Lockdown2176": 1000000000,
  }
